### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by DeaconDesperado** [slacy/minimongo#27]
I don't think the package as fetched from pip includes the README.rst anymore?  I'm having trouble installing it:

Downloading/unpacking minimongo
  Running setup.py egg_info for package minimongo
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/var/folders/tz/gvwfckmx06vg9107bqd3mmynbxzgjs/T/pip-build/minimongo/setup.py", line 58, in <module>
        long_description=LONG_DESCRIPTION,
    NameError: name 'LONG_DESCRIPTION' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/var/folders/tz/gvwfckmx06vg9107bqd3mmynbxzgjs/T/pip-build/minimongo/setup.py", line 58, in <module>

    long_description=LONG_DESCRIPTION,

NameError: name 'LONG_DESCRIPTION' is not defined

**Comment by goanpeca** [comment]
@slacy Has this been fixed?

Seems like a simple fix but gives a very bad impression when trying to test the library for the first time

**Comment by superbobry** [comment]
Yes, this has been fixed by PR#36 and merged into `master`. However, there wasn't a PyPI release since then. I think we can do a release after Python3 support (see #34).
